### ISSUE TITLE
Confusion about setting up Spectatorview with MRTK 2.4.0 and Unity 2019.4.5f1.

### ISSUE THREAD

**Issue by oddruud** [microsoft/MixedReality-SpectatorView#441]
Hello, 

We have a hololens 2 project using the advised combination of MRTK 2.4.0 and Unity 2019.4.5f1. I recently wanted to add SpectatorView such that we could make promotional content using an ARCore or ARKit enabled phone. I followed the setup steps under "Build a package to share with your team", compiling the master branch codebase which resulted in the "com.microsoft.spectatorview.1.2.0" package. I then added this local package to my existing hololens 2 project. This resulted in errors in various classes of arsubsystem such as  

Library\PackageCache\com.unity.xr.arsubsystems@2.2.0-preview.3\Runtime\ImageTrackingSubsystem\XRImageTrackingSubsystem.cs(57,30): error CS0506: 'XRImageTrackingSubsystem.Destroy()': cannot override inherited member 'Subsystem.Destroy()' because it is not marked virtual, abstract, or override

Library\PackageCache\com.unity.xr.arsubsystems@2.2.0-preview.3\Runtime\SessionSubsystem\XRSessionSubsystem.cs(123,30): error CS0506: 'XRSessionSubsystem.Destroy()': cannot override inherited member 'Subsystem.Destroy()' because it is not marked virtual, abstract, or override

This shows me that SpectatorView is running on an older version of ARFoundation, checking the Spectatorview package json I find that it uses;

"com.unity.xr.arcore": "2.2.0-preview.2",
"com.unity.xr.arfoundation": "2.1.4",
"com.unity.xr.arkit": "2.1.1"  

I have tried updating the AR packages here to newer versions but that just results in different errors. So before finding myself too deep into this potential rabbithole I just want to check what is the right course of action here. I am guessing im running into problems since I am using 2019.4.5f1 (as advised for MRTK) while SpectatorView is not compatible with this version of Unity 2019. Correct? Is there a way of making SpectatorView work with MRTK 2.4.0 and Unity 2019.4.5f1?

**Comment by piener87** [comment]
Hello,
I am also interested in this thread.
Can the spectator view be used only with Unity 2018?
Furthermore, the documentation at the website https://microsoft.github.io/MixedReality-SpectatorView/README.html has not yet been updated.

**Comment by BeLe07** [comment]
Also interested in this topic because I'm not more able to get it working using Unity 2019.4.16f1.

**Comment by Bathur** [comment]
@oddruud @piener87 @BeLe07 
Hi, guys.
I have been working with the latest version of unity2019LTS, the current version number is unity2019.4.16f1. 
But I think the problems encountered by unity2019.4.x should be similar. 
I wonder if you have a solution now? 
None of the examples provided in this repository work correctly! 
And it seems that this repository has not been maintained and updated for a long time.

**Comment by oddruud** [comment]
It looks like this project has been abandoned. I will probably be making my own promotional capture solution using ARFoundation

**Comment by jasimmj** [comment]
> It looks like this project has been abandoned. I will probably be making my own promotional capture solution using ARFoundation

This is sad
